apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: jpl-ferrari-jobhunt-springboot:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/jobhunter
        - name: SPRING_DATASOURCE_USERNAME
          value: jobhunter
        - name: SPRING_DATASOURCE_PASSWORD
          value: hunterpw
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_JPA_DATABASE-PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080